### ISSUE TITLE
No way to open YouTube links in the Vanced app instead of the normal one.

### ISSUE THREAD

**Issue by SamuelBucher** [moffatman/chan#145]
There doesn't seem to be a way to make it so Chance opens YouTube links in the YouTube Vanced app, which I have been using exclusively. I know that this technically isn't an issue, more like a feature request, but it would greatly improve the user experience of people who don't like ads.

**Comment by moffatman** [comment]
Is there special handling for Vanced in other 4chan clients? I'm able to get it to work on my phone by disabling the "Open link in..." handling on the official YouTube client and enabling it for Vanced. I know there are some changes in recent Android versions though. What's your device and Android version?

**Comment by moffatman** [comment]
Does youtube vanced open when you click links in other apps?

**Comment by SamuelBucher** [comment]
No. Looks like it's a me issue then. Sorry for bothering you.
But if you can give advice on how to fix this, I would really appreciate it.

**Comment by moffatman** [comment]
I think Redmi uses MIUI? If so, you could try the following instructions which worked for me on MIUI 13 / Android 12: https://www.reddit.com/r/androidapps/comments/8q01hh/how_do_i_make_youtube_links_open_up_in_youtube/ibgwpfe/

**Comment by SamuelBucher** [comment]
Thank you, it worked.
