### ISSUE TITLE
Feature request: soundposts

### ISSUE THREAD

**Issue by AlexZorzi** [moffatman/chan#146]
In some boards WebM with sound are not allowed. Anons came up with soundposts as a solution.

Resources:
https://sleazyfork.org/en/scripts/31045-4chan-external-sounds
https://greasyfork.org/en/scripts/402682-4chan-sounds-player

How to make a file with audio:

Choose an image/webm file
Choose an audio file (.ogg recommended but .mp3 etc generally also work)
Upload your audio file to one of the file hosts below (catbox.moe is recommended)
Grab the resulting audio link and encode it [here](https://meyerweb.com/eric/tools/dencoder/)  
You should end up with something like ```https%3A%2F%2Ffiles.catbox.moe%2F76o66i.ogg```
Add the encoded audio link to the image's filename, in the format [sound={url}]
Example: ```[sound=https%3A%2F%2Ffiles.catbox.moe%2F76o66i.ogg].png```
The audio tag may be anywhere in the filename, with text before or after it
Upload your image to 4chan
One example of complete filename could be ```Still_into_you[sound=files.catbox.moe%2Fojai4u.m4a].webm```

List of usable hosts:

catbox.moe
dmca.gripe
lewd.se
pomf.cat
zz.ht

**Comment by moffatman** [comment]
Do you have some example post I can test it out on?. This is not as complex as I thought, I thought the audio url was inside the image file data (Exif tags?) for some reason. But if it's in the filename, it should be pretty easy.

**Comment by AlexZorzi** [comment]
Here's an example https://boards.4channel.org/vt/thread/40362324#p40363186
