### ISSUE TITLE
WEBM player problems on Android

### ISSUE THREAD

**Issue by BigDogg99** [moffatman/chan#149]
1. Randomly, audio keeps playing in the background after closing a buffering video.
2. The video duration is incorrect.

**Comment by moffatman** [comment]
Also see >>/chance/3214

**Comment by moffatman** [comment]
Going to call this one done as of the [new version](https://github.com/moffatman/chan/releases/tag/v1.0.32-forked-engine), if you see the duration problem again, you can re-open the ticket. Ideally with a link to any webm which triggers the issue.
