### ISSUE TITLE
Android App Freezed

### ISSUE THREAD

**Issue by Sdash24** [moffatman/chan#170]
After opening a random thread in /b/ the app freezed permanently. So I can't post this issue on /chance/ (Idk where it exist in the web).
tried clearing cache,
forced stopped,
restarted device
still didn't worked.

**Comment by moffatman** [comment]
Please explain more details. What does freezed mean? Can you post a screenshot?

**Comment by Sdash24** [comment]
> Please explain more details. What does freezed mean? Can you post a screenshot?

Unfortunately deleted the SS
but it was stuck in loading screen

**Comment by Sdash24** [comment]
haven't tested the latest version it was for v1.0.31

**Comment by moffatman** [comment]
Ah, please try the newest version and see if there is any difference

**Comment by Sdash24** [comment]
how can I access the /chance/ board outside of Chance?
actually It's more comfortable than github lol
@moffatman

**Comment by moffatman** [comment]
@Sdash24 you can find it here: https://boards.chance.surf/chance/

**Comment by Sdash24** [comment]
Closing it
I'll use the board for any issue I get. Thanks
