### ISSUE TITLE
Scrollbar is really hard to drag

### ISSUE THREAD

**Issue by Colemakqwerty** [moffatman/chan#175]
On my previous Android phone with a flat screen (Realme 8) I could never get the scrollbar to work so I assumed that it cannot be dragged.

Now I have a Galaxy S23 Ultra and i tried again using the s-pen and I found it that you actually can drag the scrollbar but with my finger I can't get it to work at all. If I couldn't do it before with a flat screen, now it's pretty much guaranteed impossible with the curved screen.

It also doesn't help that I'm using gesture navigation so trying to fiddle with the the tiny scrollbar always ends up triggering the gesture for "back".

I think the simplest way to fix this would be to have the option to change the thickness of the scrollbar. Or at least I assume so cause I dont have the same issue on KurobaEX which has a much thicker scrollbar.

Is there a trick I'm missing?

Cheers

**Comment by moffatman** [comment]
Probably I'll just bump up the scrollbar thickness a lot, you're right it's pretty useless atm
