### ISSUE TITLE
Jitter when scrolling

### ISSUE THREAD

**Issue by Nexxol** [moffatman/chan#176]
It’s kinda nauseating. Instead of scrolling smoothly it jitters. Using iPhone 14 pro 

https://streamable.com/mxixii

**Comment by moffatman** [comment]
Can you record the screen with hidden performance overlay enabled?
Double tap the little "Development News" text at the top of the settings page, and you'll be able to "toggle FPS graph" in a popup.
It will help me figure out what's wrong, I don't have any iPhone 14 pro, I suspect this issue will only occur on ProMotion phones.

**Comment by Nexxol** [comment]
> Can you record the screen with hidden performance overlay enabled?
> Double tap the little "Development News" text at the top of the settings page, and you'll be able to "toggle FPS graph" in a popup.
> It will help me figure out what's wrong, I don't have any iPhone 14 pro, I suspect this issue will only occur on ProMotion phones.

Yep I believe it’s an issue with promotion. https://streamable.com/09lqrj

**Comment by moffatman** [comment]
Thanks, the recording is really helpful

**Comment by moffatman** [comment]
Looks like it is a common issue in all flutter apps, apple changed something in new iOS update. So it'll be fixed in the next update. https://github.com/flutter/flutter/issues/131319

**Comment by moffatman** [comment]
Btw, I don't think is gonna be fixed on my end, but apparently it's back to normal in iOS 17.

**Comment by moffatman** [comment]
Closing because app seems fine on iOS 17
