### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#182]
first it blocked (may be banned) me, then when i connected through vpn i get verifications that never end looping...

and then without a vpn it still wants verification...

can't search.

**Comment by moffatman** [comment]
Not me asking for the verification....it's cloudflare. What site are you on, just 4chan?

**Comment by moffatman** [comment]
Idk. Can you view and post on frenschan.org in your web browser?

**Comment by spergware** [comment]
Any workaround for not being able to post when on NordVPN?
