### ISSUE TITLE
app irresponsive during captcha solving

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#183]
when cloudflare is asking
 for captchas, going back sometime has the app not responding...
![ResizedImage_2023-11-19_12-53-25_2384](https://github.com/moffatman/chan/assets/122597295/d69bba34-fa0d-45ef-9df6-56627255ecfd)

usual screen when it doesn't...
![ResizedImage_2023-11-19_12-53-53_1258](https://github.com/moffatman/chan/assets/122597295/0b4ba6c6-a5c5-44c4-a2e5-3b47a96795ff)

**Comment by moffatman** [comment]
Have you tried just clearing cookies?

**Comment by moffatman** [comment]
OK, the problem is, I do get this forever looping cloudflare in my Android phone on the search screen, but I don't get the "not responding". Are you able to get any logs from Android about this event? Or can you show it in a video recording? Thx

**Comment by moffatman** [comment]
What's your phone model, I can search to see if any submitted crash logs are applicable

**Comment by moffatman** [comment]
I need to know what phone model and OS version to look for, there are a lot of errors

**Comment by moffatman** [comment]
I can't help you unless you tell me your phone model and OS version

**Comment by moffatman** [comment]
Idk, I don't think search page works on any android at the moment, will look into it in a little while

**Comment by moffatman** [comment]
Can you show a video or something of the crash? It works for me. Thx

**Comment by moffatman** [comment]
Yes and please do a video recording of all these issues not just a screenshot, it makes it a lot more clear for me to try it myself. Thx.

**Comment by moffatman** [comment]
The error doesn't make any sense. Is your phone date/time wrong??

**Comment by moffatman** [comment]
If your time is more than 6 months off i would expect that error.....

**Comment by moffatman** [comment]
Of course there is https to load images. The question is why your operating system is reporting the server's cert is expired.

**Comment by moffatman** [comment]
Ok, wow, I actually got the same error following your steps. Thx for finding it! Will look at it more....

**Comment by moffatman** [comment]
Not a good idea, just change the URL will be best

**Comment by moffatman** [comment]
Can you show it in a video, the search works for me
