### ISSUE TITLE
When browsing threads, thread info covers up the thread summary.

### ISSUE THREAD

**Issue by persson1589** [moffatman/chan#185]
![Screenshot_20231216_220225](https://github.com/moffatman/chan/assets/49785692/4bdb4e7d-f3af-4158-b050-879707526065)

When browsing threads, thread info(amount of comments, last bump etc) covers up the first lines in the threads overview. This is annoying because you don't fully grasp what the thread is about. Disabling this thread info  graphic should be a setting in settings.

**Comment by moffatman** [comment]
It's on purpose, you can just make the thread rows taller in settings if you want. If the metadata was inline with the text you would just see less text..... Or there's an option to have it on its "own row" and never overlap.

**Comment by persson1589** [comment]
> It's on purpose, you can just make the thread rows taller in settings if you want. If the metadata was inline with the text you would just see less text..... Or there's an option to have it on its "own row" and never overlap.

I would like an option to completely hide the metadata and increase the lines showed in every thread in thread overview. I have tried all settings but the problem is still present.

**Comment by persson1589** [comment]
> It's on purpose, you can just make the thread rows taller in settings if you want. If the metadata was inline with the text you would just see less text..... Or there's an option to have it on its "own row" and never overlap.

I found the setting now. Hmm thx for the info. I'm closing this issue.
