### ISSUE TITLE
Catalog grid mode OP image respect aspect ratio?

### ISSUE THREAD

**Issue by HASJ** [moffatman/chan#187]
Is it possible?

**Comment by moffatman** [comment]
No one asked for it yet, its not implemented

**Comment by HASJ** [comment]
> No one asked for it yet, its not implemented

Can I ask for it?

**Comment by moffatman** [comment]
Yeah i'll add it at some point sure

**Comment by HASJ** [comment]
> Yeah i'll add it at some point sure

Thanks nigga. Love you.

**Comment by moffatman** [comment]
Added it here a7e3e62
