### ISSUE TITLE
Text editing interface does not respect iOS/Android style choice

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#189]
When switched to iOS interface, using "Select text" in threads; the text selector is in as android style not iOS.

**Comment by moffatman** [comment]
?

**Comment by moffatman** [comment]
What does it mean variable font? you are able to import ttf or otf to use as custom font already.

**Comment by moffatman** [comment]
I really have no idea. you got to try it out

**Comment by moffatman** [comment]
Can you explain how I can try this myself? what's the font file? and what features are missing?

**Comment by moffatman** [comment]
Can you post a font file?

**Comment by moffatman** [comment]
And what feature is missing? What should i try to turn on?

**Comment by moffatman** [comment]
I UNDERSTAND THAT VARIABLE FONTS HAVE MORE FEATURES AVAILABLE. WHAT ARE YOU ASKING ME TO FIX? DO YOU WANT SOME INTERFACE IN CHANCE TO CHANGE THE SLANT WIDTH OR OPTICAL SIZE OF YOUR FONT?

**Comment by moffatman** [comment]
I picked InterVariable.ttf and the interface looks different. what's wrong?

**Comment by moffatman** [comment]
I don't understand your comment. What doesn't do what?

**Comment by moffatman** [comment]
" But it doesn't do that. Only modifies the regular weight." What is "it" here? I dont understand what you mean that there is some feature working today that is incomplete?
Since I don't have any way really to customize the chosen font today.

**Comment by moffatman** [comment]
OK. so that's what you want? Weight and width sliders?

**Comment by moffatman** [comment]
So what do you want? Can you draw a picture? Since we are not getting anywhere. I DONT KNOW WHAT YOU WANT TO CHANGE!!!!!!!!!!!!!!!!!
Is the problem that BOLD TEXT with a VARIABLE FONT in CHANCE is being drawn with a wrong method? It is a dumb multiplication of the defatul variant? and not properly using variable parameter?

**Comment by moffatman** [comment]
So what's the complaint. Does "regular" text look wrong? Or just bold/weight-adjusted text?

**Comment by moffatman** [comment]
Thx. i get it now, it will be fixed

**Comment by moffatman** [comment]
Sorry, is there a problem with static font too?

What I fixed, I noticed bold and normal text in Inter.ttf looked the same. now it is bolded properly

For Google Fonts, looks like they serve the variants as different files. it could be possible to get chance to use the different ones smartly. but don't expect it soon, it's a lot of work.
