### ISSUE TITLE
Issues with settings redesign

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#192]
First, what you see FIRST landing to settings...
![ResizedImage_2024-03-31_13-20-09_2593](https://github.com/moffatman/chan/assets/122597295/35fb9291-1257-4df8-9ee3-053a943da715)
  > It doesn't look Cupertino design (may be not also Material 3 design)

Last, layout seem changed to centre. It's like this:
![ResizedImage_2024-03-31_13-20-34_2594](https://github.com/moffatman/chan/assets/122597295/a6fe4e30-0876-439b-a1e7-ac5b685a577d)

**Comment by moffatman** [comment]
Sure i can reduce the centering. But whats wrong with first screenshot

**Comment by moffatman** [comment]
I like it its my design . i am not gonna change anything with this substanceless comments
