### ISSUE TITLE
App not opening/loading boards (API down?)

### ISSUE THREAD

**Issue by bakphooon** [moffatman/chan#193]
api.chance.surf shows a 404 error. I can't load any boards or use the Chance board. App hangs on title screen when opening after closing after a fresh install.

**Comment by moffatman** [comment]
https://api.chance.surf/ always just shows 404. a more useful url would be https://api.chance.surf/preferences/sites. Which works fine for me. And logs don't show any issue in the past few hours.

**Comment by bakphooon** [comment]
> https://api.chance.surf/ always just shows 404. a more useful url would be https://api.chance.surf/preferences/sites. Which works fine for me. And logs don't show any issue in the past few hours.

My VPN was blocking it for some reason x(
Sorry about that, can't believe I never considered it was my VPN. All seems to be working good.

**Comment by moffatman** [comment]
Wow. I think some places do have a problem with the goofy URL ".surf". maybe i should go back to the less suspicious looking "cloudfunctions.net" version.
