### ISSUE TITLE
Scrollbar is too glitchy

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#195]
After the new update, scrollbar is seem to resize more often in threads (before it only did in appearance settings). There are long thread where scrollbar had to resize after scrolling up (or down)–scrollbar sets to small according to how much you scroll up (or down) and may be as the grows thread (but, here, we are swiping down so thread from up to where we are; shouldn't load as like as if we were to scroll down).

Scrollbar glitches as you scroll in a thread that is long – mostly a cross-thread post that you jump into. Scrollbar freezes a place, and stutters badly, then slowly sizes smaller.

\*scroll up is swipe down and scroll down is swipe up.*
\*depends if you use the scrollbar or just swipe.

**Comment by moffatman** [comment]
Yep I know. unlikely to be fixed for many complicated reasons.
