### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#198]
Search for Reddit should also have these options:
- Sort:
  - Hot
  - New
  - Top
  - Contro
  - Rising
  - [maybe] Relevance
- Type:
  - Text only
  - Images only
  - Gallery only
  - Videos only
  - [maybe] Polls only
 
And subreddit/users in the result!??

Another Subreddit wiki/info is not accessible (may be, 4chan doesn't have it anyways).

-- --
### Two questions

1. How many posts Chan can load from reddit?

2. Reddit video playback as they load (not to wait to completely download it)??

**Comment by moffatman** [comment]
1. Will add the search sorts
2. Will think about type
3. I don't understand what do you mean about subreddit/users?
4. Subreddit wiki/sidebar will add it eventually
5. I don't understand your question about how many posts
6. Videos do play as they load
7. Please link an example of user flair text glitched
8. I like post flairs first personally. It's like the category, and what I'm used to from various subreddits' CSS

**Comment by moffatman** [comment]
No, it can keep loading. go to the bottom it will keep extending the list. Doesn't work? What sorting did you try and what sub, I'll try it myself. Since it always works for me.

**Comment by moffatman** [comment]
It works on /r/all. but i realized the whole extending list thing is completely broken for the new "staggered grid". So going to fix that. If you use "rows" view catalog and /r/all can't extend for you, it must be some bug I'm not experiencing.

**Comment by moffatman** [comment]
/r/all /new works for me. but i didnt see that post with 9999 images. i guess other than that. it works?

**Comment by moffatman** [comment]
What do you mean/ Where did it stop?

**Comment by moffatman** [comment]
@idontveapc 
Sure i'll fix that
can you link a post where you saw it?
thx

**Comment by moffatman** [comment]
this one just has one quote.
i get what you mean, it doesn't look the same as reddit. i was lazy and just treat it as a "greentext". maybe i can add a new display mode for reddit
but you need to find an example of the two quotes displaying wrong thing so I can understand

**Comment by moffatman** [comment]
Yeah this is my bug, fixed it https://github.com/moffatman/chan/commit/224f1cd8c24b66e92e9866c64220cde3c208f064

**Comment by moffatman** [comment]
Can you link one? I never really understood cross posts. And they don't fit well in image board structure. So maybe I didn't handle it right.

**Comment by moffatman** [comment]
What's the problem with it? Video plays fine and it links to the original in the OP

**Comment by moffatman** [comment]
I think so. reddit username search is very basic. but it should show up in subreddits

**Comment by moffatman** [comment]
I should let you move the flair tbh. but what theme are you using? for me they look different. but i use a rather standard theme (Tomorrow) (dark)

**Comment by moffatman** [comment]
Good catch, next update will have fixed order fa0dbe2c6be34e320972b301f4eb6803d1b02776
