### ISSUE TITLE
[QnA]

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#200]
Why is everything completely transparent on webpages (webpage previews/WebView's)?

**Comment by moffatman** [comment]
Sorry I don't understand, can you post a screenshot?

**Comment by moffatman** [comment]
Have you got "blur effects" disabled in settings? Otherwise idk

**Comment by moffatman** [comment]
I'll have to look into it, since it looks a lot better on my Mac

<img width="627" alt="image" src="https://github.com/moffatman/chan/assets/789275/eda62359-ca33-4ea6-8b43-d3534e0dc804">

**Comment by moffatman** [comment]
Again please put a screenshot when you ask these arbitrary design questions
