### ISSUE TITLE
Reddit image (emote), and thumbnails in comments

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#201]
- Reddit emotes(may be emoji) show up empty in the comments. It's in .gif (depends if it moves), and when seen raw in the comments it's the text: <pre><img src="https://www.redditstatic.com/marketplace-assets/v1/core/emotes/snoomoji_emotes/t5_2r73m9/7502.gif"></pre>
<pre><code><img src="https://www.redditstatic.com/marketplace-assets/v1/core/emotes/snoomoji_emotes/t5_2r73m9/25085.gif"></code></pre>

- When you change thumbnail position to right (as reddit, 4chan on left) it also changes the position in the comments. Which is looks bad because English goes left-to-right. I prefer it not to change in the comments, or especially not for the English language.

**Comment by moffatman** [comment]
I fixed the emotes here bd2915138d7fa629191927a6e83fcab6c0258e22

So do you want different image setting for each site? Or if I just add a setting to have different position in catalog v.s. thread, that will be good?

**Comment by moffatman** [comment]
Sorry your complaint is really detailed. Can you post an image?

**Comment by moffatman** [comment]
So what do you want?

**Comment by moffatman** [comment]
Sorry I still don't get it. Can you do a drawing with what you want to change? It is really hard to understand

**Comment by moffatman** [comment]
What do you think? I don't really like it, too much wasted space on left

<img width="728" alt="image" src="https://github.com/moffatman/chan/assets/789275/f73b29b5-9103-4b88-9ac4-891c48f576eb">
