### ISSUE TITLE
Weird! Symbol fonts don't work

### ISSUE THREAD

**Issue by idontveapc** [moffatman/chan#207]
Now the variable font does feel working properly. But when i checked for other fonts, symbol fonts don't work at all.

One for example: 
[Apple.Symbols.zip](https://github.com/user-attachments/files/17265234/Apple.Symbols.zip)

You can select but font fallback to system.

**Comment by moffatman** [comment]
Sorry what is a symbol font? And what do you expect to see?

**Comment by moffatman** [comment]
Sure, maybe it doesn't work, but is there any point of a symbol font here? I'm not adding any dingbats in Chance lol

**Comment by moffatman** [comment]
Lol I didn't do anything. but great it works now
