### ISSUE TITLE
Add option to share post as image for absolute timestamps

### ISSUE THREAD

**Issue by paradox460** [moffatman/chan#209]
Currently, if you attempt to share a post as an image, it will use your configured post information and timestamp appearance:

![IMAGE 2024-10-25 10:57:37](https://github.com/user-attachments/assets/52dd7232-f8b0-479d-b65f-8c9598984f5f)

For sharing posts as images, it can be useful to have the actual timestamp in the image:

![IMAGE 2024-10-25 10:57:39](https://github.com/user-attachments/assets/351a0ff7-0184-4585-948c-e3c113ea3777)

It would be nice to be able to swap the relative timestamp out for an absolute one, or even allow full customization of the share as image post details

**Comment by moffatman** [comment]
I don't want to bloat the app with even more options. But I agree, the relative timestamp is almost always useless. Maybe it should always put full YYYY-MM-DD HH:MM:SS format?

**Comment by paradox460** [comment]
Thats probably best.
