### ISSUE TITLE
MP4 does not load and gives an error on IOS

### ISSUE THREAD

**Issue by etisHere** [moffatman/chan#215]
Webms n etc work fine but anytime it's a mp4 the file won't load.

**Comment by etisHere** [comment]
Would like to add, using the site from a browser it works fine.. Just not on this application.

**Comment by moffatman** [comment]
i know. will be fixed soon

**Comment by Idesmi** [comment]
@moffatman Can you publish a new release?

**Comment by moffatman** [comment]
Important stuff still to do
(support for extremely obscure ukrainian imageboards #214 lol)
