### ISSUE TITLE
Almost every post gets spam-filtered

### ISSUE THREAD

**Issue by Dzialowy** [moffatman/chan#217]
There's like 1% chance the post will actually go through, usually I'm getting this

![Screenshot_20241212-113031~2](https://github.com/user-attachments/assets/bc6cb3a5-0005-4a48-a1a2-1a54f947747a)

Content of the post doesn't matter, happens on everything.

**Comment by moffatman** [comment]
send me your network logs (button in bottom of data settings)

**Comment by Dzialowy** [comment]
> send me your network logs (button in bottom of data settings)

[network.log.gz](https://github.com/user-attachments/files/18112900/network.log.gz)

**Comment by moffatman** [comment]
I deleted your comment since its best not to keep that file publicly available

**Comment by moffatman** [comment]
4chan is giving you hard captchas. Turn off the auto-submit and babysit your captcha answers for a few posts

**Comment by Dzialowy** [comment]
Alright, thanks
